name: 13 - Using Caching
on:
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Wheter to execute cache step 

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: '20.x'
            - name: Install dependencies
              working-directory: 13-caching/react-app
              run: |
                npm ci
            - name: Testing
              working-directory: 13-caching/react-app
              run: |
                npm run test
            - name: Building
              working-directory: 13-caching/react-app
              run: |
                npm run build
            - name: Deploying to nonprod
              run: |
                echo "Deploying to nonprod"